default_model_config_key: gemini_flash_zero_temp

model_configurations:
  gemini_flash_zero_temp:
    description: "Gemini 2.0 Flash model with zero temperature for deterministic output"
    client_module: "models.gemini_model"
    client_function_name: "invoke_gemini_with_structured_output"
    llm_params:
      model_name: "gemini-2.0-flash" # 사용 가능한 모델명으로 수정
      temperature: 0.0
    prompt_path: "models/review_analysis_prompt/v0.1.prompt" 